name: Update

on:
  schedule:
    # Runs "At minute 15 past every 4th hour." (see https://crontab.guru)
    - cron: '15 */4 * * *'
jobs:
  build:
    name: Trigger update every hour
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: |
          curl -X GET 'https://sendemails.deno.dev/'
