name: Update

on:
  schedule:
    # Runs "At minute 0 past every 4th hour." (see https://crontab.guru)
    - cron: '0 */4 * * *'
jobs:
  build:
    name: Trigger update every hour
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: |
          curl -L -X POST 'https://gjclmptpvaepykpghadl.functions.supabase.co/opentrust/sendEmails' -H 'Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}' --data '{"name":"Functions"}'
